### ISSUE TITLE
Some exported FIT files are incompatible with Garmin

### ISSUE THREAD

**Issue by d10i** [endurabyte/FitEdit#13]
# Steps to reproduce
1. Import [15535326668.zip](https://github.com/endurabyte/FitEdit/files/15415979/15535326668.zip) after extracting it. This is a pool swimming session that was exported directly from Garmin Connect
2. Load it (Select it -> Selection -> Load)
3. Export (Select it -> Selection -> Export)

Export only works if another file is imported, loaded, exported and unloaded first (see https://github.com/endurabyte/FitEdit/issues/12).

Once exported, when uploading it on [Garmin Connect](https://connect.garmin.com/modern/import-data), Garmin says "We don't support the file type you tried to import.".

Also importing and loading the same exported file in FitEdit does not show the heartrate chart, so I suspect there is something wrong with the exported file.

**Comment by nref** [comment]
Hi @d10i , and thanks for the report. I'll have a look at this ASAP!

**Comment by nref** [comment]
Fixed in 5.0.0. The issue was FitEdit did not support multipart FIT files. Now it does.

Thanks again!
